# Generated by Django 5.2.8 on 2025-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
