# Generated by Django 5.2.8 on 2025-11-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection'),
        ),
    ]
