# Generated by Django 5.2.8 on 2025-11-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_location_collection'),
        ('my_profile', '0002_alter_my_profile_exp_date_alter_my_profile_sub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.my_profile'),
        ),
    ]
