# Generated by Django 5.2.8 on 2025-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collection_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
