# Generated by Django 5.2.8 on 2025-12-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
