# Generated by Django 5.2.8 on 2025-12-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_product_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(default='MNTH3-PREM', max_length=254),
            preserve_default=False,
        ),
    ]
