# Generated by Django 5.2.8 on 2025-12-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='free_tier_records',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
