# Generated by Django 5.2.8 on 2025-11-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_side', models.CharField(max_length=80, unique=True)),
                ('b_side', models.CharField(blank=True, max_length=80)),
                ('large_hole', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
        ),
    ]
