# Generated by Django 5.2.8 on 2025-11-21 17:08

import django.db.models.deletion
import record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.ForeignKey(default=record.models.get_default_artist, on_delete=django.db.models.deletion.SET_DEFAULT, to='record.artist', to_field='name'),
        ),
    ]
