# Generated by Django 5.2.8 on 2025-11-21 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('record', '0002_artist_alter_record_notes_record_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection', to_field='name'),
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.location', to_field='name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='a_side',
            field=models.CharField(max_length=80),
        ),
    ]
