# Generated by Django 5.2.8 on 2025-11-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_name'),
        ('record', '0003_record_collection_record_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.location', to_field='name'),
        ),
    ]
