# Generated by Django 5.2.8 on 2025-12-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_record_collection_alter_record_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
