# Generated by Django 5.2.8 on 2025-12-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='hide_record',
            field=models.BooleanField(default=False),
        ),
    ]
