# Generated by Django 5.2.8 on 2025-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_profile',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='my_profile',
            name='sub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
