# Generated by Django 5.2.8 on 2025-12-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_alter_my_profile_exp_date_alter_my_profile_sub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_profile',
            options={'verbose_name': 'User Profile'},
        ),
    ]
