# Generated by Django 5.2.8 on 2025-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_alter_my_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_profile',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
