# Generated by Django 5.2.8 on 2025-12-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_my_profile_default_country_my_profile_default_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_profile',
            name='num_records',
            field=models.IntegerField(default=0),
        ),
    ]
